version: "3"
services:
  db:
    image: mysql
    container_name: db_mysql_dev
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "33061:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=devdojo
    networks:
      - mysql-dev-network
    restart: always
volumes:
  mysql-data:
networks:
  mysql-dev-network:
    driver: bridge
